### ISSUE TITLE
Gazebo SImulation Problem

### ISSUE THREAD

**Issue by full0134** [ROBOTIS-GIT/ROBOTIS-OP3#107]
Hello sirs,

I am trying to get the gazebo simulation working but it seems to run into an issue. The simulation loads but then does not work. I have attached the terminal outputs below. Sorry if this is an obvious problem, as I am quite new to using ROS/Gazebo.

Gazebo:
robotis@robotis-op3 ~ $ roslaunch op3_gazebo robotis_world.launch 
... logging to /home/robotis/.ros/log/50b22eaa-40ec-11eb-b989-645d86d0e2d3/roslaunch-robotis-op3-4927.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

xacro: Traditional processing is deprecated. Switch to --inorder processing!
To check for compatibility of your document, use option --check-order.
For more infos, see http://wiki.ros.org/xacro#Processing_Order
xacro.py is deprecated; please use xacro instead
started roslaunch server http://10.42.0.1:42283/

SUMMARY
========

PARAMETERS
 * /robot_description: <?xml version="1....
 * /robotis_op3/head_pan_position/joint: head_pan
 * /robotis_op3/head_pan_position/pid/d: 0.0
 * /robotis_op3/head_pan_position/pid/i: 0.0
 * /robotis_op3/head_pan_position/pid/p: 5.0
 * /robotis_op3/head_pan_position/type: effort_controller...
 * /robotis_op3/head_tilt_position/joint: head_tilt
 * /robotis_op3/head_tilt_position/pid/d: 0.0
 * /robotis_op3/head_tilt_position/pid/i: 0.0
 * /robotis_op3/head_tilt_position/pid/p: 5.0
 * /robotis_op3/head_tilt_position/type: effort_controller...
 * /robotis_op3/joint_state_controller/publish_rate: 50
 * /robotis_op3/joint_state_controller/type: joint_state_contr...
 * /robotis_op3/l_ank_pitch_position/joint: l_ank_pitch
 * /robotis_op3/l_ank_pitch_position/pid/d: 0.0
 * /robotis_op3/l_ank_pitch_position/pid/i: 0.0
 * /robotis_op3/l_ank_pitch_position/pid/p: 50.0
 * /robotis_op3/l_ank_pitch_position/type: effort_controller...
 * /robotis_op3/l_ank_roll_position/joint: l_ank_roll
 * /robotis_op3/l_ank_roll_position/pid/d: 0.0
 * /robotis_op3/l_ank_roll_position/pid/i: 0.0
 * /robotis_op3/l_ank_roll_position/pid/p: 50.0
 * /robotis_op3/l_ank_roll_position/type: effort_controller...
 * /robotis_op3/l_el_position/joint: l_el
 * /robotis_op3/l_el_position/pid/d: 0.0
 * /robotis_op3/l_el_position/pid/i: 0.0
 * /robotis_op3/l_el_position/pid/p: 10.0
 * /robotis_op3/l_el_position/type: effort_controller...
 * /robotis_op3/l_hip_pitch_position/joint: l_hip_pitch
 * /robotis_op3/l_hip_pitch_position/pid/d: 0.0
 * /robotis_op3/l_hip_pitch_position/pid/i: 0.0
 * /robotis_op3/l_hip_pitch_position/pid/p: 50.0
 * /robotis_op3/l_hip_pitch_position/type: effort_controller...
 * /robotis_op3/l_hip_roll_position/joint: l_hip_roll
 * /robotis_op3/l_hip_roll_position/pid/d: 0.0
 * /robotis_op3/l_hip_roll_position/pid/i: 0.0
 * /robotis_op3/l_hip_roll_position/pid/p: 50.0
 * /robotis_op3/l_hip_roll_position/type: effort_controller...
 * /robotis_op3/l_hip_yaw_position/joint: l_hip_yaw
 * /robotis_op3/l_hip_yaw_position/pid/d: 0.0
 * /robotis_op3/l_hip_yaw_position/pid/i: 0.0
 * /robotis_op3/l_hip_yaw_position/pid/p: 50.0
 * /robotis_op3/l_hip_yaw_position/type: effort_controller...
 * /robotis_op3/l_knee_position/joint: l_knee
 * /robotis_op3/l_knee_position/pid/d: 0.0
 * /robotis_op3/l_knee_position/pid/i: 0.0
 * /robotis_op3/l_knee_position/pid/p: 50.0
 * /robotis_op3/l_knee_position/type: effort_controller...
 * /robotis_op3/l_sho_pitch_position/joint: l_sho_pitch
 * /robotis_op3/l_sho_pitch_position/pid/d: 0.0
 * /robotis_op3/l_sho_pitch_position/pid/i: 0.0
 * /robotis_op3/l_sho_pitch_position/pid/p: 10.0
 * /robotis_op3/l_sho_pitch_position/type: effort_controller...
 * /robotis_op3/l_sho_roll_position/joint: l_sho_roll
 * /robotis_op3/l_sho_roll_position/pid/d: 0.0
 * /robotis_op3/l_sho_roll_position/pid/i: 0.0
 * /robotis_op3/l_sho_roll_position/pid/p: 10.0
 * /robotis_op3/l_sho_roll_position/type: effort_controller...
 * /robotis_op3/r_ank_pitch_position/joint: r_ank_pitch
 * /robotis_op3/r_ank_pitch_position/pid/d: 0.0
 * /robotis_op3/r_ank_pitch_position/pid/i: 0.0
 * /robotis_op3/r_ank_pitch_position/pid/p: 50.0
 * /robotis_op3/r_ank_pitch_position/type: effort_controller...
 * /robotis_op3/r_ank_roll_position/joint: r_ank_roll
 * /robotis_op3/r_ank_roll_position/pid/d: 0.0
 * /robotis_op3/r_ank_roll_position/pid/i: 0.0
 * /robotis_op3/r_ank_roll_position/pid/p: 50.0
 * /robotis_op3/r_ank_roll_position/type: effort_controller...
 * /robotis_op3/r_el_position/joint: r_el
 * /robotis_op3/r_el_position/pid/d: 0.0
 * /robotis_op3/r_el_position/pid/i: 0.0
 * /robotis_op3/r_el_position/pid/p: 10.0
 * /robotis_op3/r_el_position/type: effort_controller...
 * /robotis_op3/r_hip_pitch_position/joint: r_hip_pitch
 * /robotis_op3/r_hip_pitch_position/pid/d: 0.0
 * /robotis_op3/r_hip_pitch_position/pid/i: 0.0
 * /robotis_op3/r_hip_pitch_position/pid/p: 50.0
 * /robotis_op3/r_hip_pitch_position/type: effort_controller...
 * /robotis_op3/r_hip_roll_position/joint: r_hip_roll
 * /robotis_op3/r_hip_roll_position/pid/d: 0.0
 * /robotis_op3/r_hip_roll_position/pid/i: 0.0
 * /robotis_op3/r_hip_roll_position/pid/p: 50.0
 * /robotis_op3/r_hip_roll_position/type: effort_controller...
 * /robotis_op3/r_hip_yaw_position/joint: r_hip_yaw
 * /robotis_op3/r_hip_yaw_position/pid/d: 0.0
 * /robotis_op3/r_hip_yaw_position/pid/i: 0.0
 * /robotis_op3/r_hip_yaw_position/pid/p: 50.0
 * /robotis_op3/r_hip_yaw_position/type: effort_controller...
 * /robotis_op3/r_knee_position/joint: r_knee
 * /robotis_op3/r_knee_position/pid/d: 0.0
 * /robotis_op3/r_knee_position/pid/i: 0.0
 * /robotis_op3/r_knee_position/pid/p: 50.0
 * /robotis_op3/r_knee_position/type: effort_controller...
 * /robotis_op3/r_sho_pitch_position/joint: r_sho_pitch
 * /robotis_op3/r_sho_pitch_position/pid/d: 0.0
 * /robotis_op3/r_sho_pitch_position/pid/i: 0.0
 * /robotis_op3/r_sho_pitch_position/pid/p: 10.0
 * /robotis_op3/r_sho_pitch_position/type: effort_controller...
 * /robotis_op3/r_sho_roll_position/joint: r_sho_roll
 * /robotis_op3/r_sho_roll_position/pid/d: 0.0
 * /robotis_op3/r_sho_roll_position/pid/i: 0.0
 * /robotis_op3/r_sho_roll_position/pid/p: 10.0
 * /robotis_op3/r_sho_roll_position/type: effort_controller...
 * /rosdistro: kinetic
 * /rosversion: 1.12.14
 * /use_sim_time: True

NODES
  /robotis_op3/
    controller_spawner (controller_manager/spawner)
  /
    gazebo (gazebo_ros/gzserver)
    gazebo_gui (gazebo_ros/gzclient)
    urdf_spawner (gazebo_ros/spawn_model)

ROS_MASTER_URI=http://10.42.0.1:11311

process[gazebo-1]: started with pid [4966]
process[gazebo_gui-2]: started with pid [4971]
process[urdf_spawner-3]: started with pid [4975]
ERROR: cannot launch node of type [controller_manager/spawner]: controller_manager
ROS path [0]=/opt/ros/kinetic/share/ros
ROS path [1]=/home/robotis/catkin_ws/src
ROS path [2]=/opt/ros/kinetic/share
[ INFO] [1608267429.074960294]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1608267429.077592434]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...
[ INFO] [1608267429.415269459]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1608267429.419324586]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...
SpawnModel script started
shutdown request: new node registered with same name
[INFO] [1608267429.967050, 0.000000]: Loading model XML from ros parameter
[INFO] [1608267429.982124, 0.000000]: Waiting for service /gazebo/spawn_urdf_model
[INFO] [1608267429.984069, 0.000000]: Calling service /gazebo/spawn_urdf_model
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/gazebo_ros/spawn_model", line 313, in <module>
    sm.callSpawnService()
  File "/opt/ros/kinetic/lib/gazebo_ros/spawn_model", line 271, in callSpawnService
    initial_pose, self.reference_frame, self.gazebo_namespace)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/gazebo_ros/gazebo_interface.py", line 28, in spawn_urdf_model_client
    rospy.wait_for_service(gazebo_namespace+'/spawn_urdf_model')
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 159, in wait_for_service
    raise ROSInterruptException("rospy shutdown")
rospy.exceptions.ROSInterruptException: rospy shutdown
[ INFO] [1608267430.359857990]: <robotNamespace> set to: //
[ INFO] [1608267430.359931330]: <topicName> set to: //robotis_op3/imu
[ INFO] [1608267430.359969095]: <frameName> set to: body_link
[ INFO] [1608267430.360012959]: <updateRateHZ> set to: 10
[ INFO] [1608267430.360041992]: <gaussianNoise> set to: 0
[ INFO] [1608267430.360073828]: <xyzOffset> set to: 0 0 0
[ INFO] [1608267430.360122969]: <rpyOffset> set to: 0 -0 0
[INFO] [1608267430.461895, 0.000000]: Spawn status: SpawnModel: Successfully spawned entity
[urdf_spawner-3] process has finished cleanly
log file: /home/robotis/.ros/log/50b22eaa-40ec-11eb-b989-645d86d0e2d3/urdf_spawner-3*.log
[ INFO] [1608267431.050111649]: Camera Plugin: Using the 'robotNamespace' param: '/'
[ INFO] [1608267431.071445666]: Camera Plugin (ns = /)  <tf_prefix_>, set to ""
[ INFO] [1608267556.775078705, 18.153000000]: waitForService: Service [/gazebo/set_physics_properties] is now available.
[ INFO] [1608267556.776317821, 18.153000000]: waitForService: Service [/gazebo/set_physics_properties] is now available.
[ INFO] [1608267557.158470679, 18.215000000]: Physics dynamic reconfigure ready.
[ INFO] [1608267557.161445120, 18.216000000]: Physics dynamic reconfigure ready.

Manager:
robotis@robotis-op3 ~ $ roslaunch op3_manager op3_manager.launch
... logging to /home/robotis/.ros/log/50b22eaa-40ec-11eb-b989-645d86d0e2d3/roslaunch-robotis-op3-5760.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://10.42.0.1:37035/

SUMMARY
========

PARAMETERS
 * /device_name: /dev/ttyUSB0
 * /gazebo: False
 * /gazebo_robot_name: robotis_op3
 * /init_file_path: /home/robotis/cat...
 * /offset_file_path: /home/robotis/cat...
 * /op3_manager/angle_unit: 30
 * /robot_file_path: /home/robotis/cat...
 * /rosdistro: kinetic
 * /rosversion: 1.12.14

NODES
  /
    op3_localization (op3_localization/op3_localization)
    op3_manager (op3_manager/op3_manager)

ROS_MASTER_URI=http://10.42.0.1:11311

process[op3_manager-1]: started with pid [5777]
process[op3_localization-2]: started with pid [5778]
[ WARN] [1608267596.775736095, 19.994000000]: Shutdown request received.
[ WARN] [1608267596.776140845, 19.994000000]: Reason given for shutdown: [new node registered with same name]
[ INFO] [1608267596.877677373]: manager->init
[ INFO] [1608267597.151671749, 20.001000000]: Torque on DXLs!
/dev/ttyUSB0 added. (baudrate: 2000000)
(/dev/ttyUSB0) [ID:  1]         XM-430 added. 
(/dev/ttyUSB0) [ID:  2]         XM-430 added. 
(/dev/ttyUSB0) [ID:  3]         XM-430 added. 
(/dev/ttyUSB0) [ID:  4]         XM-430 added. 
(/dev/ttyUSB0) [ID:  5]         XM-430 added. 
(/dev/ttyUSB0) [ID:  6]         XM-430 added. 
(/dev/ttyUSB0) [ID:  7]         XM-430 added. 
(/dev/ttyUSB0) [ID:  8]         XM-430 added. 
(/dev/ttyUSB0) [ID:  9]         XM-430 added. 
(/dev/ttyUSB0) [ID: 10]         XM-430 added. 
(/dev/ttyUSB0) [ID: 11]         XM-430 added. 
(/dev/ttyUSB0) [ID: 12]         XM-430 added. 
(/dev/ttyUSB0) [ID: 13]         XM-430 added. 
(/dev/ttyUSB0) [ID: 14]         XM-430 added. 
(/dev/ttyUSB0) [ID: 15]         XM-430 added. 
(/dev/ttyUSB0) [ID: 16]         XM-430 added. 
(/dev/ttyUSB0) [ID: 17]         XM-430 added. 
(/dev/ttyUSB0) [ID: 18]         XM-430 added. 
(/dev/ttyUSB0) [ID: 19]         XM-430 added. 
(/dev/ttyUSB0) [ID: 20]         XM-430 added. 
(/dev/ttyUSB0) [ID:200]        OPEN-CR added. 
[ INFO] [1608267598.045100598, 20.028000000]: Load offsets...
[ WARN] [1608267598.397615243, 20.038000000]: Head control - angle unit : 30
[ INFO] [1608267598.699967199, 20.047000000]: parse pose for moving init pose
[ WARN] [1608267598.704118912, 20.047000000]: Get the init gain from Dxl init file
[ INFO] [1608267598.846664266, 20.050000000]: Go to init pose
[ INFO] [1608267598.865311984, 20.050000000]: Base Module is enabled
[ INFO] [1608267598.950302469, 20.051000000]: [start] send trajectory
[ INFO] [1608267602.956757226, 20.151000000]: [end] send trajectory

**Comment by ROBOTIS-Will** [comment]
Hi @full0134 
I'm sorry about the delayed response, but I don't see a particular issue from your log.
If you see the ![image](https://user-images.githubusercontent.com/26239359/106832976-0ce06880-66d6-11eb-8aae-8d581f6c4bd9.png) icon instead of Pause ![image](https://user-images.githubusercontent.com/26239359/106832961-04882d80-66d6-11eb-969c-4b31a213c3da.png) icon at the bottom of Gazebo screen, Gazebo is not running, but waiting to be played.

**Comment by ROBOTIS-zerom** [comment]
Due to the lack of a response for an extended period, we will be closing this issue. You can always reopen it if any further questions or problems arise.
